//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/player/player_actions/player_actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/player/player_actions/player_actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Player_actions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Player_actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""player_actions"",
    ""maps"": [
        {
            ""name"": ""player_actions_map"",
            ""id"": ""607dd94f-54bb-4919-8821-73c8dcc391ec"",
            ""actions"": [
                {
                    ""name"": ""movement"",
                    ""type"": ""Value"",
                    ""id"": ""42de5896-3162-42de-9530-a8f2c7cf760a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""y_aiming"",
                    ""type"": ""Value"",
                    ""id"": ""da3a2af4-d213-4daf-9bfe-17808599ab2a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""light_punch"",
                    ""type"": ""Button"",
                    ""id"": ""b038b77e-589c-4e45-802c-8d3fc06d06c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""heavy_punch"",
                    ""type"": ""Button"",
                    ""id"": ""3450ecb0-92ad-4b09-805b-db43ae44ac66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""d17a62a1-ec80-4b4a-b8c8-ccdb62ffc3fd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""block"",
                    ""type"": ""Button"",
                    ""id"": ""6ed5a6ca-9a5f-46ea-8e6c-62cc5e543d9c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cc43ed64-d225-4d63-a272-a9e863345b46"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""de363447-2f32-4c40-8b34-5eba5fb4b313"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""46aaba55-fe9c-46db-869c-a2cb08e77e0b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""614d360b-0925-4aee-82fb-4e5b67537126"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""386a3c98-7c6d-47f9-936d-d4a29689f875"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""y_aiming"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""ff61b075-4951-4026-8d3a-0a7719127a2d"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""y_aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""556cc24d-061b-4615-8650-ee830244b287"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""y_aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e258638c-c3b9-4854-9c4f-6cb033e594b6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""y_aiming"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""c47894d5-9982-4eaa-aeb6-0bdfee216f2a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""y_aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""6d3d976b-bf6f-45c9-9af5-c6d6076f3784"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""y_aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1f1324a0-706e-4d62-861a-b8d25302b34a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""light_punch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""765a7ba9-12fe-4268-90de-bf1baf2fe9a6"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""light_punch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c3c74aa-b0ef-4837-936e-dc0fbd5cc972"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""heavy_punch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3efcc4f9-5b41-4646-9e92-d2f6b333ba67"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""heavy_punch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0405e7f0-0364-4f31-b9d1-56faeb960561"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""280daf24-7539-4cfa-b36b-3f328aec30bc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a81a8896-0794-43d3-9d37-78fac1a6166e"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eea99447-5958-4c84-936f-aa455092b18e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";controller"",
                    ""action"": ""block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // player_actions_map
        m_player_actions_map = asset.FindActionMap("player_actions_map", throwIfNotFound: true);
        m_player_actions_map_movement = m_player_actions_map.FindAction("movement", throwIfNotFound: true);
        m_player_actions_map_y_aiming = m_player_actions_map.FindAction("y_aiming", throwIfNotFound: true);
        m_player_actions_map_light_punch = m_player_actions_map.FindAction("light_punch", throwIfNotFound: true);
        m_player_actions_map_heavy_punch = m_player_actions_map.FindAction("heavy_punch", throwIfNotFound: true);
        m_player_actions_map_jump = m_player_actions_map.FindAction("jump", throwIfNotFound: true);
        m_player_actions_map_block = m_player_actions_map.FindAction("block", throwIfNotFound: true);
    }

    ~@Player_actions()
    {
        UnityEngine.Debug.Assert(!m_player_actions_map.enabled, "This will cause a leak and performance issues, Player_actions.player_actions_map.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // player_actions_map
    private readonly InputActionMap m_player_actions_map;
    private List<IPlayer_actions_mapActions> m_Player_actions_mapActionsCallbackInterfaces = new List<IPlayer_actions_mapActions>();
    private readonly InputAction m_player_actions_map_movement;
    private readonly InputAction m_player_actions_map_y_aiming;
    private readonly InputAction m_player_actions_map_light_punch;
    private readonly InputAction m_player_actions_map_heavy_punch;
    private readonly InputAction m_player_actions_map_jump;
    private readonly InputAction m_player_actions_map_block;
    /// <summary>
    /// Provides access to input actions defined in input action map "player_actions_map".
    /// </summary>
    public struct Player_actions_mapActions
    {
        private @Player_actions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Player_actions_mapActions(@Player_actions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "player_actions_map/movement".
        /// </summary>
        public InputAction @movement => m_Wrapper.m_player_actions_map_movement;
        /// <summary>
        /// Provides access to the underlying input action "player_actions_map/y_aiming".
        /// </summary>
        public InputAction @y_aiming => m_Wrapper.m_player_actions_map_y_aiming;
        /// <summary>
        /// Provides access to the underlying input action "player_actions_map/light_punch".
        /// </summary>
        public InputAction @light_punch => m_Wrapper.m_player_actions_map_light_punch;
        /// <summary>
        /// Provides access to the underlying input action "player_actions_map/heavy_punch".
        /// </summary>
        public InputAction @heavy_punch => m_Wrapper.m_player_actions_map_heavy_punch;
        /// <summary>
        /// Provides access to the underlying input action "player_actions_map/jump".
        /// </summary>
        public InputAction @jump => m_Wrapper.m_player_actions_map_jump;
        /// <summary>
        /// Provides access to the underlying input action "player_actions_map/block".
        /// </summary>
        public InputAction @block => m_Wrapper.m_player_actions_map_block;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_player_actions_map; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Player_actions_mapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Player_actions_mapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Player_actions_mapActions" />
        public void AddCallbacks(IPlayer_actions_mapActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_actions_mapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_actions_mapActionsCallbackInterfaces.Add(instance);
            @movement.started += instance.OnMovement;
            @movement.performed += instance.OnMovement;
            @movement.canceled += instance.OnMovement;
            @y_aiming.started += instance.OnY_aiming;
            @y_aiming.performed += instance.OnY_aiming;
            @y_aiming.canceled += instance.OnY_aiming;
            @light_punch.started += instance.OnLight_punch;
            @light_punch.performed += instance.OnLight_punch;
            @light_punch.canceled += instance.OnLight_punch;
            @heavy_punch.started += instance.OnHeavy_punch;
            @heavy_punch.performed += instance.OnHeavy_punch;
            @heavy_punch.canceled += instance.OnHeavy_punch;
            @jump.started += instance.OnJump;
            @jump.performed += instance.OnJump;
            @jump.canceled += instance.OnJump;
            @block.started += instance.OnBlock;
            @block.performed += instance.OnBlock;
            @block.canceled += instance.OnBlock;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Player_actions_mapActions" />
        private void UnregisterCallbacks(IPlayer_actions_mapActions instance)
        {
            @movement.started -= instance.OnMovement;
            @movement.performed -= instance.OnMovement;
            @movement.canceled -= instance.OnMovement;
            @y_aiming.started -= instance.OnY_aiming;
            @y_aiming.performed -= instance.OnY_aiming;
            @y_aiming.canceled -= instance.OnY_aiming;
            @light_punch.started -= instance.OnLight_punch;
            @light_punch.performed -= instance.OnLight_punch;
            @light_punch.canceled -= instance.OnLight_punch;
            @heavy_punch.started -= instance.OnHeavy_punch;
            @heavy_punch.performed -= instance.OnHeavy_punch;
            @heavy_punch.canceled -= instance.OnHeavy_punch;
            @jump.started -= instance.OnJump;
            @jump.performed -= instance.OnJump;
            @jump.canceled -= instance.OnJump;
            @block.started -= instance.OnBlock;
            @block.performed -= instance.OnBlock;
            @block.canceled -= instance.OnBlock;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Player_actions_mapActions.UnregisterCallbacks(IPlayer_actions_mapActions)" />.
        /// </summary>
        /// <seealso cref="Player_actions_mapActions.UnregisterCallbacks(IPlayer_actions_mapActions)" />
        public void RemoveCallbacks(IPlayer_actions_mapActions instance)
        {
            if (m_Wrapper.m_Player_actions_mapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Player_actions_mapActions.AddCallbacks(IPlayer_actions_mapActions)" />
        /// <seealso cref="Player_actions_mapActions.RemoveCallbacks(IPlayer_actions_mapActions)" />
        /// <seealso cref="Player_actions_mapActions.UnregisterCallbacks(IPlayer_actions_mapActions)" />
        public void SetCallbacks(IPlayer_actions_mapActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_actions_mapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_actions_mapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Player_actions_mapActions" /> instance referencing this action map.
    /// </summary>
    public Player_actions_mapActions @player_actions_map => new Player_actions_mapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "player_actions_map" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Player_actions_mapActions.AddCallbacks(IPlayer_actions_mapActions)" />
    /// <seealso cref="Player_actions_mapActions.RemoveCallbacks(IPlayer_actions_mapActions)" />
    public interface IPlayer_actions_mapActions
    {
        /// <summary>
        /// Method invoked when associated input action "movement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "y_aiming" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnY_aiming(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "light_punch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLight_punch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "heavy_punch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHeavy_punch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "block" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBlock(InputAction.CallbackContext context);
    }
}
